FROM openjdk:18.0-jdk as builder
WORKDIR application
ARG JAR_FILE=target/employeeservice-oauth2-0.2-SNAPSHOT.jar
COPY ${JAR_FILE} application.jar
RUN java -Djarmode=layertools -jar application.jar extract
 
FROM openjdk:18.0-jdk
WORKDIR application
COPY --from=builder application/dependencies/ ./
RUN true
COPY --from=builder application/spring-boot-loader/ ./
RUN true
COPY --from=builder application/snapshot-dependencies/ ./
RUN true
COPY --from=builder application/application/ ./

ENTRYPOINT java -Dspring.profiles.active=$PROFILE -Dspring.application.name=$APP_NAME -Dserver.port=$HTTP_SERVER_PORT -Dlegendlime.https-port=$HTTPS_SERVER_PORT -Djavax.net.ssl.trustStore=$TRUST_STORE_PATH -Djavax.net.ssl.trustStorePassword=$TRUST_STORE_PASSWORD -Djavax.net.ssl.keyStore=$KEY_STORE_PATH -Djavax.net.ssl.keyStorePassword=$KEY_STORE_PASSWORD -Djavax.net.ssl.keyStorePassword=$KEY_STORE_PASSWORD -Xmx512M -Xms512M -Djdk.tls.client.protocols=TLSv1.2 org.springframework.boot.loader.JarLauncher
